# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        # Durée de vie du cookie côté navigateur (en secondes)
        cookie_lifetime: 1800        # 30 minutes
        # Durée maximale de vie côté serveur (en secondes)
        gc_maxlifetime: 1800         # 30 minutes
        # Démarre la session automatiquement si nécessaire
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    http_method_override: true # permet de modifier la methode qui est utiliser grâce à un champs caché

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
