# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    filter_sets:
        cache: ~
        thumb_80x80:
            quality: 75
            filters:
                thumbnail: { size: [80, 80], mode: outbound }
        thumb_100x100:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        thumb_200x200:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        thumb_700x400:
            quality: 75
            filters:
                thumbnail: { size: [700, 400], mode: outbound }
        thumb_700x_auto:
            quality: 75
            filters:
                thumbnail: { size: [700, null], mode: outbound}
